apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: instavote
spec:
  minReadySeconds: 20
  replicas: 10
  template:
    spec:
      containers:
      - image: schoolofdevops/vote:v4
        name: vote
        envFrom:
          - configMapRef:
              name: vote
              optional: true
